<?php
$lang['choose_db'] = "Selezione una banca dati per proseguire";
$lang['error_in_method'] = "Qualcosa è andato storto nell'eseguire il %s";
$lang['module_doesnot_exist'] = "Errore. Il modulo %s non esiste";
$lang['error_in_module'] = "Errore. Qualcosa è andato storto nel caricare il modulo %s";
$lang['generic_error'] = "Errore. Si prega di consultare il log degli errori per maggiori informazioni!";
$lang['no_app'] = "Errore. Nessuna applicazione disponibile. Impossibile continuare";
$lang['file_doesnt_exist'] = "Errore. Il file %s non esiste!";
$lang['login'] = "Autenticazione";
$lang['email_password_needed'] = "Entrambi i campi (e-mail e password) sono obbligatori per proseguire";
$lang['remember_me'] = "Resta connesso";

$lang['no_connect_data'] = "Errore. Nessun dato disponibile per la connessione";
$lang['no_connect_data_for_host'] = "Errore. Nessun dato disponibile per la connessione all'host %s";
$lang['driver_not_supported'] = "Il driver database %s non è attualmente supportato";

$lang['send'] = "Invia";
$lang['back'] = "Indietro";
$lang['email_present'] = "Errore. L'indirizzo %s è già presente nel database. Non è possibile proseguire";
$lang['email_not_valid'] = "Errore. L'indirizzo %s non sembra un indirizzo email valido. Non è possibile proseguire";
$lang['not_enough_data'] = "Non ci sono abbastanza dati per continuare";
$lang['login_data_not_valid'] = "Errore. E-mail e/o password non validi!";
$lang['cannot_delete_file'] = "Errore. Non è stato possibile cancellare il file %s";
$lang['cannot_delete_dir'] = "Errore. Non è stato possibile cancellare la cartella %s";
$lang['no_app_error'] = "Errore. Impossibile continuare senza specificare l'applicazione";
$lang['tb_config_missing'] = "Manca il file di configurazione delle tabelle";
$lang['config_file_missing'] = "Manca il file di configurazione [%s]";

$lang['attention'] = "Attenzione";

$lang['search-fn'] = "Cerca funzione";
$lang['data_mng'] = "Gestione dati";
$lang['options'] = "Opzioni";
$lang['other'] = "Altro";
$lang['select_tb'] = "Seleziona tabella";
$lang['restart'] = "Riavvia";
$lang['close_application'] = "Chiudi applicazione";
$lang['show_all'] = "Mostra tutto";
$lang['advanced_search'] = "Ricerca avanzata";
$lang['import'] = "Importa DB";
$lang['sql_expert_search'] = "Ricerca per esperti SQL";
$lang['contextual_search_in'] = "Ricerca contestuale (%s)";

$lang['user_mng'] = "Gestione utenti";
$lang['add_new_user'] = "Aggiungi un nuovo utente";

$lang['new'] = "Nuovo";
$lang['new_file'] = "Nuovo file";
$lang['export'] = "Esporta";
$lang['backup'] = "Backup";
$lang['find_replace'] = "Trova e sostituisci";
$lang['vocabulary_mng'] = "Gestione vocabolario";

$lang['multiupload'] = "Caricamento multiplo di file";
$lang['load_file_to_proceed'] = "Carica uno o più file prima di procedere";
$lang['filename'] = "Nome file";
$lang['ext'] = "Estensione";
$lang['link_at_table'] = "Collegamento alla tabella";
$lang['link_at_id'] = "Collegamento all'ID";
$lang['add_link'] = "Aggiungi collegamento";
$lang['click_drag_to_upload'] = "Clicca o trascina qui i file per caricarli";
$lang['drop_to_upload'] = "Rilascia qui i file per caricarli";


$lang['bdus_web'] = "Sito web di BraDypUS";
$lang['user_guide'] = "Guida all'utilizzo";
$lang['changelog'] = "Lista dei cambiamenti";
$lang['copyright'] = "Copyright";
$lang['template_mng'] = "Gestione maschere";
$lang['install_patch'] = "Installa correzione";
$lang['system_translate'] = "Traduzione sistema";
$lang['front_page_editor'] = "Prima pagina";

$lang['app_data_editor'] = "Info applicazione";
$lang['disabled'] = "Disabilitato";

$lang['edit_tbs_data'] = "Tabelle applicazione";
$lang['edit_flds_data'] = "Campi tabelle";
$lang['free_sql'] = "esegui SQL";
$lang['backup_2_drive']  = "Backup su drive";
$lang['restore_from_drive'] = "Ripristina da drive";
$lang['chat'] = "Chat";
$lang['ip'] = "IP";
$lang['most_recent_records'] = "Record più recenti";
$lang['fast_search'] = "Ricerca veloce";

$lang['not_enough_privilege'] = "Siamo spiacenti, ma non disponi dei privilegi sufficienti per accedere a questa funzione";
$lang['tb_missing'] = "Errore. Manca il nome della tabella di riferimento. Impossibile proseguire";
$lang['parameter_missing'] = "Errore! Mancano i seguenti parametri: %s";
$lang['no_record_found'] = "Nessun record trovato";
$lang['x_record_found'] = "%s record trovati";
$lang['contains'] = "Contiene";
$lang['is_exactly'] = "È esattamente";
$lang['doesnt_contain'] = "Non contiene";
$lang['starts_with'] = "Comincia con";
$lang['ends_with'] = "Finisce con";
$lang['is_empty'] = "È vuoto";
$lang['is_not_empty'] = "Non è vuoto";
$lang['bigger'] = "È più grande di";
$lang['smaller'] = "È più piccolo di";
$lang['order'] = "Ordinamento";
$lang['test_sql'] = "Verifica query";
$lang['test_ok_x_found'] = "Query verificata con successo. Trovati %s record";
$lang['available_fields'] = "Campi disponibili";
$lang['query'] = "Query";
$lang['utilities'] = "Utilità";
$lang['test_error'] = "Errore nella query!";
$lang['close'] = "Chiudi";
$lang['show_query'] = "Mostra query";
$lang['read'] = "Leggi";
$lang['edit'] = "Modifica";
$lang['erase'] = "Cancella";
$lang['display'] = "Mostra";
$lang['add'] = "Aggiungi";
$lang['toggle_select_all'] = "Seleziona/Deseleziona tutto";
$lang['reload'] = "Ricarica";
$lang['confirm_erase'] = "Sei sicuro di volere cancellare questa/e scheda/e? Questa azione sarà defintiva e non sarà possibile tornare indietro";
$lang['logout_confirm_title'] = "Sei sicuro di volere chiudere l'applicazione?";
$lang['logout_confirm_body'] = "La cartella temporanea dell'utente verrà svuotata e le impostazioni dell'utente verrano salvate nella banca dati</p>";
$lang['pay_attention'] = "Attenzione prego";
$lang['cancel'] = "Annulla";
$lang['continue'] = "Continua";
$lang['save'] = "Salva";
$lang['save_as_new'] = "Salva come nuova";
$lang['confirm_save_as_new'] = "Sei sicuro di volere salvare questa scheda come nuova? Attenzione: i dati dei plugin e i link manuali non verranno duplicati!";
$lang['cannot_get_ip_for_system'] = "Impossibile recuperare l'IP per il sistema operativo %s";
$lang['debug'] = "Log degli errori";
$lang['log_delete'] = "Il log degli errori è stato cancellato";
$lang['log_not_deleted'] = "Errore. Non è stato possibile cancellare il log degli errori";
$lang['invert_log'] = "Inverti grep";
$lang['info'] = "Informazioni";
$lang['no_id_to_view'] = "Errore. Non è stato specificato alcun record da modificare";
$lang['close_all'] = "Chiudi tutto";
$lang['select_row_to_continue'] = "Seleziona almeno un record per continuare";
$lang['x_files_linked'] = "%s file collegati alla presente scheda";
$lang['download'] = "Scarica";
$lang['unlink'] = "Scollega";
$lang['image_preview'] = "Anteprima imagine";
//user
$lang['user_mng'] = "Gestione utenti";
$lang['name'] = "Nome";
$lang['email'] = "Indirizzo email";
$lang['password'] = "Password";
$lang['privilege'] = "Privilegio d'accesso";
$lang['super_admin'] = "Super amministratore";
$lang['admin'] = "Amministratore";
$lang['writer'] = "Lettura & Scrittura";
$lang['self_writer'] = "Lettura & Scrittura propri record";
$lang['reader'] = "Lettura";
$lang['waiting'] = "Attesa";
$lang['edit_user'] = "Modifica l'utente";
$lang['user_data_saved'] = "I dati dell'utente sono stati salvati con successo";
$lang['user_data_not_saved'] = "Errore. Non è stato possibile salvare i dati dell'utente";
$lang['confirm_erase_user'] = "Sei sicuro di volere cancellare definitivamente l'utente?";
$lang['user_deleted'] = "L'utente è stato cancellato";
$lang['user_not_deleted'] = "Errore! Non è stato possibile cancellare l'utente";
$lang['confirm'] = "Conferma";
$lang['all_fields_needed'] = "Tutti i campi sono obbligatori per proseguire";
$lang['partial_success_saved'] = "Solo alcuni record (%s) sono stati salvati con successo. Gli altri (%s) hanno prodotto errore";
$lang['success_saved'] = "Tutti i dati sono stati salvati senza errori";
$lang['error_saved'] = "Errore. Non è stato possibile salvare i dati";
$lang['confirm_delete'] = "Sei sicuro di volere cancellare questa/e scheda/e? Questa azione sarà defintiva e non sarà possibile tornare indietro";
$lang['multiple_edit_alert'] = "Attenzione! Si stanno modificando %s record contemporaneamente! ( id: %s). I controlli in tempo reale sui campi sono stati disattivati";
$lang['no_id_provided'] = "Attenzione. Non è stato specificato nessun record da cancellare";
$lang['partially_deleted_with_count'] = "Attenzione. %s record sono stati salvati senza errori. Non è stato possibile cancellare %s";
$lang['all_record_deleted'] = "I dati sono stati cancellati senza errori";
$lang['no_record_deleted'] = "Errore. Nessun dato è stato cancellato";
$lang['too_much_records'] = "Attenzione! È stato richiesto la visualizzazione di %s record contemporaneamente. Questo potrebbe provocare lunghe attese e il blocco del sistema, che per questo motivo è stato impostato ad un limite massimo di %s record.";

$lang['details_in_log'] = "Per maggiori dettagli si veda il log degli errori";

$lang['show_query_text'] = "Mostra query";
$lang['query_text'] = "Testo della query eseguita";
$lang['save_query_as'] = "Salva query con nome";
$lang['export_query'] = "Esporta query";
$lang['reload_query'] = "Ricarica query";
$lang['export_select_format'] = "Seleziona il formato di esportazione";
$lang['available_exports'] = "Esportazioni disponibili";
$lang['error_erasing_file'] = "Errore nella cancellazione del file: %s";
$lang['success_erasing_file'] = "Il file %s è stato cancellato senza errori";
$lang['export_success'] = "L'esportazione è stata eseguita senza problemi";
$lang['export_error'] = "Errore nell'eseguire l'esportazione.";
$lang['export_dir_empty'] = "Nessuna esportazione disponibile!";

$lang['saved_queries'] = "Ricerche salvate";
$lang['no_saved_queries'] = "Nessuna ricerca salvata";
$lang['share'] = "Condividi";
$lang['unshare'] = "Termina la condivisione";
$lang['execute_query'] = "Esegui query";
$lang['ok_sharing_query'] = "La query è stata condivisa";
$lang['error_sharing_query'] = "Errore, la query non è stata condivisa";
$lang['ok_unsharing_query'] = "La query è stata resa privata";
$lang['error_unsharing_query'] = "Errore, la query non è stata resa privata";
$lang['ok_erasing_query'] = "La query è stata cancellata";
$lang['error_erasing_query'] = "Errore, la query non è stata cancellata";
$lang['ok_saving_query'] = "La query è stata salvata";
$lang['error_saving_query'] = "Errore, non è stato possibile salvare la query";
$lang['name_for_query_to_save'] = "Inserire il nome con il quale salvare la query";
$lang['query_name_is_required'] = "Il nome della query è obbligatorio";
$lang['saved_query_does_not_exist'] = "La query salvata con id %s non esiste";

$lang['no_voc_available'] = "Nessun vocabolario disponibile";
$lang['no_action_defined'] = "Nessuna azione da eseguire";
$lang['no_def_available_for_voc'] = "Nessuna voce disponibile per il vocabolario %s";
$lang['vocs'] = "Vocabolari";
$lang['available_vocs'] = "Vocabolari disponibili";
$lang['defs'] = "Definizioni";
$lang['ok_sort_update'] = "L'ordine è stato aggiornato";
$lang['error_sort_update'] = "Errore, non è stato possibile aggiornare l'ordine";
$lang['drag_to_sort'] = "Trascina per riordinare";
$lang['edit_def'] = "Modifica la definizione";
$lang['ok_def_update'] = "La definizione è stata aggiornata";
$lang['error_def_update'] = "Errore, non è stato possibile aggiornare la definizione";
$lang['confirm_delete_def'] = "Sei sicuro di volere cancellare questa defiizione?";
$lang['ok_def_erase'] = "La definizione è stata cancellata";
$lang['error_def_erase'] = "Errore, la definizione non è stata cancellata";
$lang['def'] = "Definizione";
$lang['voc'] = "Vocabolario";
$lang['new_voc'] = "Nuovo vocabolario";
$lang['new_def'] = "Nuova definizione";
$lang['ok_def_added'] = "La definizione è stata salvata";
$lang['error_def_added'] = "Errore, la definizione non è stata salvata";
$lang['voc_def_required'] = "Sia il nome del vocabolario che la definizione sono necessarie per proseguire";


$lang['no_bup_present'] = "Nessun backup presente nel sistema";
$lang['backup_now'] = "Esegui backup";
$lang['ok_backup'] = "Backup eseguito con successo";
$lang['error_backup'] = "Errore, il backup non è stato eseguito";

$lang['select_tb_search'] = "Seleziona la tabella dove eseguire il cerca/sostituisci";
$lang['select_fld_search'] = "Seleziona il campo dove eseguire il cerca/sostituisci";
$lang['search_term'] = "Termine cercato";
$lang['replace_term'] = "Termine di sostituizione";
$lang['all_fields_required'] = "Tutti i campi devono essere completati per proseguire";

$lang['confirm_search_replace'] = "Sei sicuro di volere cercare nella tabella <strong>%s</strong>, nel campo <strong>%s</strong> il valore <mark>%s</mark> e sostituirlo con <mark>%s</mark>. Questa azione sarà irreversibile";
$lang['ok_search_replace'] = "La sostituzione è stata eseguita. Sono stati processati %s record";
$lang['error_search_replace'] = "Errore, non è stato possibile eseguire la sostituzione";

$lang['edit_frontpage'] = "Modifica la prima pagina";
$lang['no_php_allowed'] = "Non è possibile usare codice PHP";
$lang['ok_edit_file'] = "Il file è stato modificato";
$lang['error_edit_file'] = "Error, il file non è stato modificato";

$lang['delete_log'] = "Cancella il log";
$lang['live_track'] = "Osserva il log in tempo reale";

$lang['no_tmpl_available'] = "Nessuna maschera disponibile per questa tabella";
$lang['tb'] = "Nome tabella";
$lang['context'] = "Contesto di utilizzo";
$lang['ok_tmpl_set'] = "La preferenza della maschera è stata salvata";
$lang['error_tmpl_set'] = "Errore, la preferenza della maschera non è stata salvata";
$lang['default'] = "Predefinito";

$lang['ok_file_updated'] = "Il file è stato aggiornato";
$lang['error_file_updated'] = "Errore, il file non è stato aggiornato";

$lang['no_files_found'] = "Nessun file è stato trovato nella cartella %s";
$lang['upload_preview'] = "Anteprima del caricamento";
$lang['proceed'] = "Procedi";
$lang['dont_import'] = "Non importare";
$lang['erase_link'] = "Cancella link";
$lang['ok_data_save'] = "I dati sono stati salvati";
$lang['error_data_save'] = "Errore, i dati non sono stati salvati";
$lang['partial_data_save'] = "Errore, non tutti i dati sono stati salvati";

$lang['system_translate'] = "Tradutore sistema";
$lang['select_lang_to_edit'] = "Seleziona una lingua da modificare";
$lang['new_lang_code_two_digits'] = "Codice della nuova lingua (due lettere)";
$lang['lang_lenth_must_be_two'] = "Il codice della nuova lingua deve essere di due lettere";
$lang['ok_lang_create'] = "Il file della nuova lingua è stato creato";
$lang['error_lang_create'] = "Errore, il file della nuova lingua non è stato creato";
$lang['ok_language_update'] = "Il file di lingua è stato aggiornato";
$lang['error_language_update'] = "Errore, il file di lingua non è stato aggiornato";
$lang['show_incomplete_translations'] = "Mostra solo le traduzioni da completare";
$lang['show_all_translations'] = "Mostra tutte le traduzioni";

$lang['not_valid_import_driver'] = "Non si dispone ancora di una procedura per l'importazione per il driver %s";
$lang['importing_for_driver'] = "Si sta importanto per il motore DB %s";
$lang['ok_import_file_backup'] = "L'importazione è stata eseguita e il vecchio database è stato salvato nella cartella delle esportazioni con il nome %s";
$lang['error_import'] = "Errore, l'importazione non è stata eseguita";

$lang['wrong_filetype'] = "Tipo di file sbagliato. Possono essere caricati solo file *.sql o *.gz";
$lang['cannot_open_imported_file'] = "Impossibile aprire il file %s per l'importazione";
$lang['cannot_point_to_offset'] = "Non è possibile mettere il puntatore del file all'offset: %s";
$lang['cannot_read_file_at_offset'] = "Non è possibile leggere il file al offset dato";
$lang['wait_dont_close'] = "Si prega di attendere senza chiudere la finestra";
$lang['ok_import_complete'] = "Importazione avvenuta senza problemi. È ora possibile chiudere la finestra";
$lang['import_loading'] = "Il processo dell'importazione è in corso...";
$lang['error_in_query'] = "Una query ha restituito un errore. Impossibile prosseguire";
$lang['import_details_log'] = "Sono stati elaborati:<br />%s linee<br />%s query<br />%s bytes.<br />Processo completo al %s%";

$lang['not_empty'] = "Questo campo non può essere vuoto";
$lang['int'] = "Questo campo ammette solo valori numerici";
$lang['email_check'] = "Il valore inserito non sembra essere un indirizzo email valido";
$lang['no_dupl'] = "Il valore inserito è già stato usato per questo campo. Il campo non ammette duplicati";
$lang['range'] = "Il valore inserito non è compreso nella gamma prevista";
$lang['regex'] = "Il valore inserito non è ben formattato";
$lang['no_data_to_save'] = "Il modulo non contiene cambiamenti da salvare nella banca dati";
$lang['errors_in_form'] = "Il modulo contiene errori. I dati non sono stati salvati. Si prega di ricontrollare prima di proseguire";
$lang['ajax_error'] = "Attenzione. È occorso un errore del sistema e non è stato possibile controllare il valore!";
$lang['no_rules_for'] = "Errore! Non ci sono regole per questo tipo di controllo";

$lang['rs'] = "Relazioni stratigrafiche";
$lang['is_covered_by'] = "È coperto da";
$lang['is_cut_by'] = "È tagliato da";
$lang['carries'] = "Gli si appoggia";
$lang['is_filled_by'] = "È riempito da";
$lang['covers'] = "Copre";
$lang['cuts'] = "Taglia";
$lang['leans_against'] = "Si appoggia a ";
$lang['fills'] = "Riempie";
$lang['is_the_same_as'] = "Uguale a";
$lang['is_bound_to'] = "Si lega a ";
$lang['ok_relation_erased'] = "La relazione è stata cancellata";
$lang['error_relation_erased'] = "Errore. La relazione non è stata cancellata";
$lang['rs_all_fields_required'] = "Tutti i campi sono necessari per insrire una nuova relazione stratigrafica";
$lang['relation_already_exist'] = "Errore. La relazione non è stata aggiunta, probabilmente una relazione tra questi due campi già esiste.";
$lang['ok_relation_add'] = "La relazione è stata aggiunta";

$lang['lost_passsword'] = "Password dimenticata";
$lang['register_new_user'] = "Registra un nuovo utente";
$lang['enter_email_to_get_password'] = "Inserire l'indirizzo email per recuperare la password";
$lang['forgot_text'] = "Una email con la procedura di recupero della password è stata mandata all'indirizzo %s. Si prega di controllare la posta e seguire le istruzioni.";
$lang['email_not_found'] = "L'indirizzo email fornito non è presente nel database";
$lang['lost_password_email_subject'] = "Richiesta di recupero password per database BraDypUS";
$lang['lost_password_email_text'] = "Salve,\n ricevete questo messaggio perché è stato richiesto il recupero della password associato a questo indirizzo email.\nPer recuperare la password si prega di andare al seguente indirizzo:\n%s\nNota bene: se non avete richiesto di recuperare la password si prega di ignorare questo messaggio email.\n\nCordiali saluti\n";
$lang['error_sending_email'] = "Errore nell'inviare il messaggio. Si prega di contattare un amministratore";
$lang['reset_password'] = "Ressetta la password";
$lang['new_password'] = "Inserisci la nuova password";
$lang['new_password_bis'] = "Ripeti la nuova password";
$lang['greeting'] = "Salve %s";
$lang['pass_empty_or_not_match'] = "Le password sono vuote o non sono uguali. Ricontrollare per procedere";
$lang['ok_password_update'] = "La password è stata cambiata, è possibile ore proseguire";
$lang['error_password_update'] = "Errore. La password non è stata cambiata";
$lang['alert_email_important'] = "Attenzione. È necessario inserire un indirizzo email attivo. Tutti i messaggi del sistema, compreso quello di conferma di accesso alla banca dati verranno inviati a questo indirizzo.";
$lang['ok_user_add'] = "L'utente è stato aggiunto al database ma non sarà possibile accedervi finché un amministratore avrà valutato e autorizzato l'accesso ai dati. Un messaggio email di conferma è stato spedito all'indirizzo %s.";
$lang['error_user_add'] = "Errore. L'utente non è stato aggiunto al database";
$lang['email_signature'] = "\nLo staff di BraDypUS\nCommunicating Cultural Heritage\nhttp://bradypus.net\n--------\nATTENZIONE: questa è un messaggio generato automaticamente. Si prega di non rispondere. Per ogni dubbio o domanza si prega di scrivere a db@bradypus.net";
$lang['new_user_email_subject'] = "Notifica registrazione utenza BraDypUS";
$lang['new_user_email_text'] = "Gentile utente, \n le inviamo questa email per confermare che la sua utenza al database %s di BraDypUS è stata creata con successo.\n Non sarà possibile raggiungere i dati finché un amministratore del sistema non abbia valutato e confermato il vostro accesso.\nRiceverete presto una email di notifica a questo stesso indirizzo.";
$lang['new_user_adm_email_text'] = "Gentile amministratore del database %s di BraDypUS, \nUn nuovo utente ha richiesto di accedere alla banca dati %s.\nI suoi dati di registrazione sono:\nnome: %s\nemail: %s\n";

$lang['harris_matrix'] = "Matrix di Harris";
$lang['query_produced_no_result'] = "La query non ha prodotto nessun risultato";
$lang['cannot_write_in_tmp_file'] = "Impossibile scrivere nel file temporaneo";
$lang['dotfile_doesnot_exist'] = "Il file DOT non è stato trovato";
$lang['cicle_problem'] = "Problema di ciclicità. Si prega di controllare meglio le relazioni stratigrafiche";
$lang['error_dot_cmd'] = "Il commando DOT ha restituito un errore";


$lang['links_avaliable'] = "Collegamenti con questa scheda:";
$lang['core_links'] = "Collegamenti automatici";
$lang['links_in_table'] = "%s schede nella tabella %s";
$lang['no_core_links'] = "Nessun collegamento automatico disponibile";

$lang['ok_userlink_erased'] = "Il link è stato cancellato";
$lang['error_userlink_erased'] = "Errore. Il link non è stato cancellato";
$lang['user_links'] = "Collegamenti manuali";
$lang['all_links_saved'] = "Tutti i link sono stati salvati";
$lang['some_links_saved'] = "Alcuni link sono stati salvati, altri no. Maggiori informazioni nel log degli errori";
$lang['no_link_saved'] = "Errore. Nessun link è stato salvato";
$lang['no_user_links'] = "Nessun collegamento disponibile per questo record";

$lang['delete_link'] = "Cancella collegamento";
$lang['new_link'] = "Aggiungi un nuovo collegamento";
$lang['select_tb_to_continue'] = "Seleziona una tabella per continuare";
$lang['save_links'] = "Collega file ai record selezionati";


$lang['print'] = "Stampa";
$lang['print_all'] = "Stampa tutto";
$lang['print_record'] = "Stampa record";

$lang['saved_charts'] = "Grafici salvati";
$lang['count'] = "Conteggio";
$lang['sum'] = "Somma";
$lang['add_bar'] = "Aggiungi colonna";
$lang['remove_bar'] = "Rimuovi colonna";
$lang['define_series'] = "Definisci le serie";
$lang['define_function'] = "Definisci la funzione";
$lang['bar'] = "Colonna";
$lang['label'] = "Etichetta";
$lang['field'] = "Campo";
$lang['build_chart'] = "Costruisci grafico";
$lang['no_value'] = "Nessun valore";
$lang['chart'] = "Grafico";
$lang['download_img'] = "Scarica immagine (png)";
$lang['save_chart_as'] = "Salva grafico con nome";
$lang['chart_name'] = "Nome del grafico";
$lang['ok_save_chart'] = "Il grafico è stato salvato";
$lang['error_save_chart'] = "Errore. Il grafico non è stato salvato. Maggiori dettagli nel log degli errori";
$lang['no_chart_available'] = "Nessun grafico salvato.";
$lang['ok_chart_erase'] = "Il grafico è stato cancellato";
$lang['error_chart_erase'] = "Errore. Il grafico non è stato cancellato";
$lang['ok_update_chart'] = "Il grafico è stato aggiornato";
$lang['error_update_chart'] = "Errore. Il grafico non è stato aggiornato. Maggiori dettagli nel log degli errori";
$lang['sql_not_allowed'] = "Le seguenti funzioni SQL non sono ammessi per motivi di sicurezza e verranno automaticamente rimossi dal testo della query";
$lang['text'] = "Testo";
$lang['edit_chart'] = "Modifica grafico";

$lang['reload_sys_required'] = "Per rendere effettiva la scelta è necessario riavviare il sistema";

$lang['error_getting_geodata'] = "Errore nel recuperare i dati geografici. Maggiori dettagli nel log degli errori";
$lang['view_on_map'] = "Visualizza sulla mappa";
$lang['view_all_records_on_map'] = "Visualizza tutta la tabella sulla mappa";
$lang['x_geodata_available'] = "%s geometrie riferite a questa scheda";
$lang['no_geodata_available'] = "Nessun dato geografico disponibile per i risultati di questa ricerca";
$lang['syntax_example'] = "Esempio di sintassi";
$lang['not_valid_syntax'] = "Il valore %s non segue la sintassi necessaria";
$lang['point'] = "Punto";
$lang['line'] = "(Poli) Linea";
$lang['polygon'] = "Poligono";
$lang['ok_insert_geodata'] = "Il dato geografico è stato salvato nella banca dati";
$lang['error_insert_geodata'] = "Errore. Il dato geografico non è stato salvato nella banca dati";
$lang['ok_delete_geodata'] = "Il dato geografico è stato cancellato";
$lang['error_delete_geodata'] = "Error. Il dato geografico non è stato cancellato";
$lang['geodata'] = "Dati geografici";
$lang['draw_point'] = "Disegna punto";
$lang['draw_line'] = "Disegna (poli)linea";
$lang['draw_polygon'] = "Disegna poligono";
$lang['ok_update_geometry'] = "La geoemtria è stata aggiornata";
$lang['error_update_geometry'] = "Errore. La geoemtria non è stata aggiornata";
$lang['navigate'] = "Naviga";
$lang['identify'] = "Identifica";
$lang['confirm_erase_feature'] = "Sei sicuro di volere cancellare definitivamente questo elemento?";
$lang['no_geodata_present_create'] = "Non ci sono dati geografici per questa tabella, ma è possibile crearli";
$lang['map_already_opened'] = "La mappa è già stata aperta in un tab. Non è possibile aprire una seconda istanza!";

$lang['ok_save_fld_data'] = "I dati del campo sono stati salvati";
$lang['error_save_fld_data'] = "Errore. I dati del campo non sono stati salvati";

$lang['ok_save_tb_data'] = "I dati della tabella sono stati salvati";
$lang['error_save_tb_data'] = "Errore. I dati della tabella non sono stati salvati";

$lang['system_email'] = "Email di sistema";
$lang['send_email'] = "Invia messaggio email";
$lang['recipients'] = "Destinatari";
$lang['sender'] = "Mittente";
$lang['content'] = "Contenuto";
$lang['subject'] = "Oggetto";
$lang['body'] = "Corpo del messaggio";
$lang['recipient_subject_body_required'] = "È necessario specificare i destinatari, l'oggetto e il corpo del messaggio per proseguire";
$lang['automatic_email_signature'] = "\n\n---\nQuesta è una email inviata da un amministrattore della banca dati %s del sistema BraDypUS.";
$lang['no_user_with_selected_privilege'] = "Non esiste alcun utente nel database avete i privilegi specificati";
$lang['ok_mail_sent_to_users'] = "Il messaggio è stato inviato senza problemi ai seguenti utenti: %s";
$lang['error_mail_sent_to_users'] = "Non è stato possibile inviare il messaggio ai seguenti utenti: %s";

$lang['history'] = "Storico";
$lang['ok_history_erased'] = "Lo storico delle modifiche è stato cancellato";
$lang['error_history_erased'] = "Errore. Lo storico delle modifiche non è stato cancellato";
$lang['history_is_empty'] = "Lo storico delle modifiche è vuoto";

$lang['ok_file_sorting_update'] = "L'ordine dei file allegati è stato cambiato";
$lang['error_file_sorting_update'] = "Errore. Non è stato possibile cambiare l'ordine";

$lang['run_free_sql'] = "Esegui una query SQL libera";


$lang['file_gallery'] = "Galleria dei file di %s";


// Preferences
$lang['user_preferences'] = "Preferenze utente";
$lang['result_pagination'] = "Impaginazione risultati";
$lang['infinite_scroll'] = "Scorrimento infinito";
$lang['pages'] = "Divisione in pagine";
$lang['user_lang'] = "Lingua utente";
$lang['open_module'] = "Apri modulo";
$lang['pref_set'] = "L'impostazione è stata salvata";
$lang['user_data'] = "Dati utente";
$lang['save_pref_in_db'] = "Salva le tue preferenze nel database per ricaricarle automaticamente nella prossima sessione";
$lang['pref_saved_in_db'] = "Le preferenze sono state salvate nel database";
$lang['pref_not_saved_in_db'] = "Errore. Le preferenze non sono state salvate nel database";
$lang['most_recent_no'] = "Numero dei record più recenti da visualizzare";
$lang['only_positive_integers_allowed'] = "Sono permesso solo numeri interi positivi!";
$lang['preview_flds'] = "Campi anteprima";
$lang['ok_preview_set'] = "La lista dei campi di anteprima è stata salvata";
$lang['default_values'] = "Valori predefiniti";

//GEOFACE
$lang['crs'] = "Sistema di coordinate di riferimento";
$lang['x_y_required'] = "Sia il valore x che quello y sono obbligatori";
$lang['add_coordinates'] = "Aggiungi coordinate";

// Attach file to record
$lang['file_data_missing'] = "Mancano i dati necessari per il caricamento del file";
$lang['error_uploading_file'] = "Errore nel caricamento del file. Impossibile procedere";
$lang['error_saving_file'] = "Errore nel salvare i dati del file. Impossibile proseguire";
$lang['error_adding_link'] = "Errore nel salvare il link. Impossibile proseguire";
$lang['file_uploaded_and_attached'] = "Il file è stato correttamente caricato e collegato";
$lang['replace_file'] = "Sostituisci file";
$lang['click_drag_link_file'] = "Carica file e collega a questo record";

// EMPTY CACHE DIR
$lang['empty_cache'] = "Svuota cache";
$lang['ok_cache_emptied'] = "La cache è stata svuotata";
$lang['error_cache_not_emptied'] = "Errore. Non è stato possibile svuotare la cache";
$lang['confirm_empty_cache'] = "Sei sicuro di volere svuotare la cache dell'applicazione? La cache aiuta a rendere più veloce il database, ma va eleminata se sono state affettuate modifiche nella struttura del layout";
$lang['empty_cache_waiting'] = "Attenzione. È in corso lo svuotamento della cache";


$lang['import_geodata'] = "Importa dati geografici";
$lang['empty_or_wrong_geojson'] = "Errore. Il file geojson caricato è vuoto o non ben formattato";
$lang['upload_file'] = "Carica file";
$lang['set_matching_fields'] = "Definisci i campi identificativi corrispondenti";
$lang['confirm_import_geodata'] = "Si prega di confirmare l'importazione di dati geografici per la tabella <code>%s</code> unendo nel database il campo <code>%s</code>con il campo esterno <code>%s</code>";
$lang['import_erase_previous_data'] = "Importa e cancella i dati geografici preesistenti";
$lang['import_dont_erase_previous_data'] = "Importa senza cancellare i dati geografici preesistenti";
$lang['geodata_ok_uploaded'] = "Nessun errore nel processo di importazione. %s geometrie sono state caricate";
$lang['geodata_error_uploaded'] = "C'è stato qualche errore nel caricare i dati geografici. Nessuna geometria è stata caricata";

$lang['app_is_frozen'] = "Attenzione. Questa applicazione è stata congelata. È possibile leggere tutte le schede ed eseguire ricerche ma non è possibile modificare i dati";
$lang[''] = "";

$lang[''] = "";
$lang[''] = "";
$lang[''] = "";
$lang[''] = "";
$lang[''] = "";
$lang[''] = "";
$lang[''] = "";
$lang[''] = "";
$lang[''] = "";
